upgrade_lookup = [
    {"id": 0, "type": "object", "object": "Cursor"},
    {"id": 1, "type": "object", "object": "Cursor"},
    {"id": 2, "type": "object", "object": "Cursor"},
    {"id": 3, "type": "object", "object": "Cursor"},
    {"id": 4, "type": "object", "object": "Cursor"},
    {"id": 5, "type": "object", "object": "Cursor"},
    {"id": 6, "type": "object", "object": "Cursor"},
    {"id": 7, "type": "object", "object": "Grandma"},
    {"id": 8, "type": "object", "object": "Grandma"},
    {"id": 9, "type": "object", "object": "Grandma"},
    {"id": 10, "type": "object", "object": "Farm"},
    {"id": 11, "type": "object", "object": "Farm"},
    {"id": 12, "type": "object", "object": "Farm"},
    {"id": 13, "type": "object", "object": "Factory"},
    {"id": 14, "type": "object", "object": "Factory"},
    {"id": 15, "type": "object", "object": "Factory"},
    {"id": 16, "type": "object", "object": "Mine"},
    {"id": 17, "type": "object", "object": "Mine"},
    {"id": 18, "type": "object", "object": "Mine"},
    {"id": 19, "type": "object", "object": "Shipment"},
    {"id": 20, "type": "object", "object": "Shipment"},
    {"id": 21, "type": "object", "object": "Shipment"},
    {"id": 22, "type": "object", "object": "Alchemy lab"},
    {"id": 23, "type": "object", "object": "Alchemy lab"},
    {"id": 24, "type": "object", "object": "Alchemy lab"},
    {"id": 25, "type": "object", "object": "Portal"},
    {"id": 26, "type": "object", "object": "Portal"},
    {"id": 27, "type": "object", "object": "Portal"},
    {"id": 28, "type": "object", "object": "Time machine"},
    {"id": 29, "type": "object", "object": "Time machine"},
    {"id": 30, "type": "object", "object": "Time machine"},
    {"id": 31, "type": "global_multiplier", "objectName": ''},
    {"id": 32, "type": "global_multiplier", "objectName": ''},
    {"id": 33, "type": "global_multiplier", "objectName": ''},
    {"id": 34, "type": "global_multiplier", "objectName": ''},
    {"id": 35, "type": "global_multiplier", "objectName": ''},
    {"id": 36, "type": "global_multiplier", "objectName": ''},
    {"id": 37, "type": "global_multiplier", "objectName": ''},
    {"id": 38, "type": "global_multiplier", "objectName": ''},
    {"id": 39, "type": "global_multiplier", "objectName": ''},
    {"id": 40, "type": "global_multiplier", "objectName": ''},
    {"id": 41, "type": "global_multiplier", "objectName": ''},
    {"id": 42, "type": "global_multiplier", "objectName": ''},
    {"id": 43, "type": "object", "object": "Cursor"},
    {"id": 44, "type": "object", "object": "Grandma"},
    {"id": 45, "type": "object", "object": "Farm"},
    {"id": 46, "type": "object", "object": "Factory"},
    {"id": 47, "type": "object", "object": "Mine"},
    {"id": 48, "type": "object", "object": "Shipment"},
    {"id": 49, "type": "object", "object": "Alchemy lab"},
    {"id": 50, "type": "object", "object": "Portal"},
    {"id": 51, "type": "object", "object": "Time machine"},
    {"id": 52, "type": "gold_cookie_multiplier", "object": ''},
    {"id": 53, "type": "gold_cookie_multiplier", "object": ''},
    {"id": 54, "type": "global_multiplier", "object": ''},
    {"id": 55, "type": "global_multiplier", "object": ''},
    {"id": 56, "type": "global_multiplier", "object": ''},
    {"id": 57, "type": "object", "object": "Grandma"},
    {"id": 58, "type": "object", "object": "Grandma"},
    {"id": 59, "type": "object", "object": "Grandma"},
    {"id": 60, "type": "object", "object": "Grandma"},
    {"id": 61, "type": "object", "object": "Grandma"},
    {"id": 62, "type": "object", "object": "Grandma"},
    {"id": 63, "type": "object", "object": "Grandma"},
    {"id": 64, "type": "object", "object": "Grandma"},
    {"id": 65, "type": "global_multiplier", "object": ''},
    {"id": 66, "type": "global_multiplier", "object": ''},
    {"id": 67, "type": "object", "object": "Grandma"},
    {"id": 68, "type": "global_multiplier", "object": ''},
    {"id": 69, "type": "object", "object": "Grandma"},
    {"id": 70, "type": "global_multiplier", "object": ''},
    {"id": 71, "type": "object", "object": "Grandma"},
    {"id": 72, "type": "global_multiplier", "object": ''},
    {"id": 73, "type": "object", "object": "Grandma"},
    {"id": 74, "type": "object", "object": "Grandma"},
    {"id": 75, "type": "cursor_multiplier", "object": ''},
    {"id": 76, "type": "cursor_multiplier", "object": ''},
    {"id": 77, "type": "cursor_multiplier", "object": ''},
    {"id": 78, "type": "cursor_multiplier", "object": ''},
    {"id": 79, "type": '', "object": ''},
    {"id": 80, "type": "global_multiplier", "object": ''},
    {"id": 81, "type": "global_multiplier", "object": ''},
    {"id": 82, "type": "object", "object": "Cursor"},
    {"id": 83, "type": "gold_cookie_multiplier", "object": ''},
    {"id": 84, "type": "global_multiplier", "object": ''},
    {"id": 85, "type": "global_multiplier", "object": ''},
    {"id": 86, "type": "gold_cookie_multiplier", "object": ''},
    {"id": 87, "type": "global_multiplier", "object": ''},
    {"id": 88, "type": "global_multiplier", "object": ''},
    {"id": 89, "type": "global_multiplier", "object": ''},
    {"id": 90, "type": "global_multiplier", "object": ''},
    {"id": 91, "type": '', "object": ''},
    {"id": 92, "type": "global_multiplier", "object": ''},
    {"id": 93, "type": "global_multiplier", "object": ''},
    {"id": 94, "type": "global_multiplier", "object": ''},
    {"id": 95, "type": "global_multiplier", "object": ''},
    {"id": 96, "type": "global_multiplier", "object": ''},
    {"id": 97, "type": "global_multiplier", "object": ''},
    {"id": 98, "type": "global_multiplier", "object": ''},
    {"id": 99, "type": "object", "object": 'Antimatter condenser'},
    {"id": 100, "type": "object", "object": 'Antimatter condenser'},
    {"id": 101, "type": "object", "object": 'Antimatter condenser'},
    {"id": 102, "type": "object", "object": 'Antimatter condenser'},
    {"id": 103, "type": "object", "object": 'Grandma'},
    {"id": 104, "type": "global_multiplier", "object": ''},
    {"id": 105, "type": "global_multiplier", "object": ''},
    {"id": 106, "type": "global_multiplier", "object": ''},
    {"id": 107, "type": "global_multiplier", "object": ''},
    {"id": 108, "type": "global_multiplier", "object": ''}
];